"use client";
import { useEffect, useMemo, useState } from "react";
import { ArrowDownRight, ArrowUpRight, Atom, Bot, BrainCircuit, Check, ChevronRight, Cpu, Download, Eye, Globe2, HeartPulse, Languages, Menu, Orbit, Rocket, Send, ShieldCheck, Sparkles, X } from "lucide-react";

type Lang="fr"|"ar";
type Project={id:number;name:string;domain:string;description:string};
type Program={id:number;name:string;description:string;externalUrl:string};
type Service={id:number;title:string;description:string;domain:string};
type Post={id:number;title:string;content:string;category:string;author:string;viewCount:number;downloadCount:number};
type Location={id:number;country:string;city:string;address:string;countryCode:string};
type Overview={projects:Project[];ecosystem:Program[];consulting:Service[];latestPosts:Post[];locations:Location[]};

const fallback:Overview={
 projects:[{id:1,name:"Space Ambition",domain:"Aérospatiale",description:"Technologies spatiales disruptives pour repousser les frontières de l'exploration."},{id:2,name:"Air Robot Taxi",domain:"Mobilité",description:"Une nouvelle génération de mobilité urbaine autonome et intelligente."},{id:3,name:"NexGen Quantum System",domain:"Quantique",description:"Informatique et capteurs quantiques pour les systèmes de demain."},{id:4,name:"Health & Performance in Soccer",domain:"Sport & Tech",description:"La donnée et l'IA au service de la performance sportive."}],
 ecosystem:[{id:1,name:"Elev8",description:"Accélérateur Deep Tech",externalUrl:"https://innovdays.intellcap.eu/elev8"},{id:2,name:"InnovDays",description:"Événements d'innovation",externalUrl:"https://innovdays.intellcap.eu/"},{id:3,name:"Constellium",description:"Réseau de partenaires",externalUrl:"https://constellium.intellcap.fr"},{id:4,name:"Startups",description:"Portfolio & incubation",externalUrl:"https://startups.intellcap.fr"}],
 consulting:[{id:1,title:"Technology Due Diligence",description:"Évaluation technique de vos actifs technologiques.",domain:"STRATEGY"},{id:2,title:"Research & Technology",description:"Accélérez vos cycles de recherche et d'innovation.",domain:"AI"},{id:3,title:"Modeling & Design",description:"Conception de systèmes complexes et performants.",domain:"AEROSPACE"},{id:4,title:"Digital Twin",description:"Simulation et optimisation par jumeau numérique.",domain:"QUANTUM"}],latestPosts:[],
 locations:[{id:1,country:"France",city:"Paris",address:"15 Rue de la Paix",countryCode:"FRA"},{id:2,country:"Luxembourg",city:"Luxembourg",address:"5 Avenue J.F. Kennedy",countryCode:"LUX"},{id:3,country:"Japan",city:"Tokyo",address:"Marunouchi, Chiyoda-ku",countryCode:"JPN"},{id:4,country:"Morocco",city:"Rabat",address:"Avenue Mohammed V",countryCode:"MOR"}]};

const copy={fr:{nav:["Programmes","Projets","Pourquoi nous","Consulting"],eyebrow:"DEEP TECH · AI · ENTREPRENEURSHIP",title:"Rejoignez le futur de",accent:"l'innovation DeepTech.",lead:"Ingénierie, intelligence artificielle et entrepreneuriat réunis dans des programmes immersifs conçus pour transformer les idées audacieuses en impact réel.",discover:"Voir les opportunités",partner:"Commencer",projects:"L'ambition, ingénierie.",projectsSub:"Des programmes audacieux portés par les équipes INTELLCAP dans l'aérospatiale, la mobilité, le quantique et l'intelligence artificielle.",services:"Notre expertise au service de votre innovation.",servicesSub:"De la due diligence à l'industrialisation, INTELLCAP accompagne chaque étape de votre parcours Deep Tech.",eco:"Construit pour façonner la prochaine génération",ecoSub:"Quatre voies de maîtrise Deep Tech — de votre premier prototype à une startup prête à l'investissement.",talent:"Rejoignez ceux qui construisent demain.",talentSub:"Explorez les opportunités de l'écosystème INTELLCAP sur nos plateformes spécialisées. Aucune candidature n'est traitée sur ce site.",talentCta:"Voir les opportunités",contact:"Devenez partenaire",contactSub:"Rejoignez l'écosystème INTELLCAP et construisons ensemble le futur.",send:"Envoyer la demande",optional:"Détails logistiques (optionnel)",loading:"Envoi en cours…"},ar:{nav:["البرامج","المشاريع","لماذا نحن","الاستشارات"],eyebrow:"تقنيات عميقة · ذكاء اصطناعي · ريادة أعمال",title:"انضم إلى مستقبل",accent:"الابتكار العميق.",lead:"الهندسة والذكاء الاصطناعي وريادة الأعمال في برامج غامرة تحول الأفكار الجريئة إلى أثر حقيقي.",discover:"عرض الفرص",partner:"ابدأ رحلتك",projects:"الطموح، بهندسة.",projectsSub:"برامج جريئة تقودها فرق INTELLCAP في الفضاء والتنقل والكم والحوسبة الذكية.",services:"خبراتنا في خدمة ابتكارك.",servicesSub:"من التدقيق التقني إلى التصنيع، نرافق كل مرحلة من رحلة التكنولوجيا العميقة.",eco:"صُمم لصناعة الجيل القادم",ecoSub:"أربعة مسارات لإتقان التكنولوجيا العميقة من النموذج الأول إلى شركة جاهزة للاستثمار.",talent:"انضم إلى صناع الغد.",talentSub:"استكشف فرص منظومة INTELLCAP على منصاتنا المتخصصة. لا تتم معالجة الطلبات هنا.",talentCta:"عرض الفرص",contact:"كن شريكًا",contactSub:"انضم إلى منظومة INTELLCAP ولنبنِ المستقبل معًا.",send:"إرسال الطلب",optional:"تفاصيل لوجستية (اختياري)",loading:"جارٍ الإرسال…"}};

const projectIcons=[Rocket,Bot,Atom,HeartPulse]; const serviceIcons=[ShieldCheck,BrainCircuit,Cpu,Orbit];
export default function Home(){
 const [lang,setLang]=useState<Lang>("fr"),[data,setData]=useState<Overview>(fallback),[menu,setMenu]=useState(false),[sent,setSent]=useState<"idle"|"loading"|"ok"|"error">("idle"); const t=copy[lang];
 useEffect(()=>{fetch("/api/backend/public/overview").then(r=>r.ok?r.json():Promise.reject()).then(setData).catch(()=>setData(fallback));},[]);
 const isAr=lang==="ar"; const year=useMemo(()=>new Date().getFullYear(),[]);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setSent("loading");const fd=new FormData(e.currentTarget);const body=Object.fromEntries(fd);body.recaptchaToken="frontend-placeholder";["surfaceAvailable","humanResources"].forEach(k=>{if(!body[k])delete body[k];else body[k]=Number(body[k]) as never;});try{const r=await fetch("/api/backend/partner-requests",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!r.ok)throw new Error();setSent("ok");e.currentTarget.reset();}catch{setSent("error");}}
 return <main dir={isAr?"rtl":"ltr"}>
  <header><a className="brand" href="#top"><span className="brandMark"><i/><i/><i/></span><b>INTELLCAP</b></a><nav className={menu?"open":""}>{t.nav.map((n,i)=><a key={n} href={`#${["projects","services","ecosystem","talents"][i]}`} onClick={()=>setMenu(false)}>{n}</a>)}<a href="#contact" className="navCta">{t.partner}<ArrowUpRight size={16}/></a></nav><button className="lang" onClick={()=>setLang(isAr?"fr":"ar")}><Languages size={17}/>{isAr?"FR":"عربي"}</button><button className="menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
  <section className="hero" id="top"><div className="noise"/><div className="orb one"/><div className="orb two"/><div className="heroCopy"><p className="eyebrow"><span/> {t.eyebrow}</p><h1>{t.title}<br/><em>{t.accent}</em></h1><p className="lead">{t.lead}</p><div className="actions"><a href="#projects" className="primary">{t.discover}<ArrowDownRight/></a><a href="#contact" className="secondary">{t.partner}<ChevronRight/></a></div><div className="proof"><div><strong>04</strong><span>Hubs mondiaux</span></div><div><strong>08</strong><span>Expertises intégrées</span></div><div><strong>360°</strong><span>Vision technologique</span></div></div></div><div className="heroVisual" aria-hidden="true"><div className="halo h1"/><div className="halo h2"/><div className="planet"><div className="planetGlow"/><span className="axis"/></div><div className="signal s1"><span>01</span> QUANTUM</div><div className="signal s2"><span>02</span> MOBILITY</div><div className="signal s3"><span>03</span> SPACE</div></div><a className="scroll" href="#projects">SCROLL <span/></a></section>
  <section id="projects" className="section projects"><SectionTitle kicker="01 — FLAGSHIP" title={t.projects} subtitle={t.projectsSub}/><div className="projectGrid">{data.projects.slice(0,4).map((p,i)=>{const Icon=projectIcons[i%4];return <article className="projectCard" key={p.id}><div className="cardTop"><span>0{i+1}</span><Icon/></div><div><small>{p.domain}</small><h3>{p.name}</h3><p>{p.description}</p></div><ArrowUpRight className="corner"/></article>})}</div></section>
  <section id="services" className="section services"><SectionTitle kicker="02 — CAPABILITIES" title={t.services} subtitle={t.servicesSub}/><div className="serviceGrid">{data.consulting.slice(0,8).map((s,i)=>{const Icon=serviceIcons[i%4];return <article key={s.id}><span><Icon size={22}/></span><div><small>{s.domain}</small><h3>{s.title}</h3><p>{s.description}</p></div></article>})}</div></section>
  <section id="ecosystem" className="section ecosystem"><div className="ecoIntro"><SectionTitle kicker="03 — ECOSYSTEM" title={t.eco} subtitle={t.ecoSub}/><div className="orbitLogo"><Globe2/><span/></div></div><div className="programs">{data.ecosystem.map((p,i)=><a key={p.id} href={p.externalUrl} target="_blank" rel="noreferrer"><span>0{i+1}</span><div><h3>{p.name}</h3><p>{p.description}</p></div><ArrowUpRight/></a>)}</div></section>
  <section id="talents" className="talents"><div className="talentArt"><div className="mesh"/><Sparkles/><span>TALENT<br/>NETWORK</span></div><div className="talentCopy"><p className="eyebrow"><span/>04 — TALENTS</p><h2>{t.talent}</h2><p>{t.talentSub}</p><a href="https://innovdays.intellcap.eu/" target="_blank" rel="noreferrer" className="primary">{t.talentCta}<ArrowUpRight/></a><div className="notice"><Check/> Redirection sécurisée · Aucun CV stocké sur ce site</div></div></section>
  {data.latestPosts.length>0&&<section className="section posts"><SectionTitle kicker="05 — INSIGHTS" title="Notes depuis la frontière" subtitle="Analyses scientifiques et technologiques de notre réseau."/><div className="postGrid">{data.latestPosts.map(p=><article key={p.id}><small>{p.category}</small><h3>{p.title}</h3><p>{p.content.slice(0,150)}…</p><footer><span><Eye size={14}/>{p.viewCount}</span><span><Download size={14}/>{p.downloadCount}</span></footer></article>)}</div></section>}
  <section id="contact" className="contact"><div className="contactLead"><p className="eyebrow"><span/>PARTNERSHIP</p><h2>{t.contact}</h2><p>{t.contactSub}</p><a href="mailto:contact@intellcap.fr">contact@intellcap.fr <ArrowUpRight/></a></div><form onSubmit={submit}><div className="formGrid"><Field name="fullName" label="Nom complet *"/><Field name="organization" label="Organisme *"/><Field name="country" label="Pays *"/><Field name="city" label="Ville *"/><Field name="email" label="Email *" type="email"/><Field name="whatsapp" label="WhatsApp (+...) *" pattern="^\+[1-9]\d{1,14}$"/></div><label className="field wide"><span>Votre besoin * <b>1000 max.</b></span><textarea name="needExpression" maxLength={1000} required rows={4}/></label><details><summary>{t.optional}<ChevronRight/></summary><div className="formGrid optional"><Field name="linkedin" label="LinkedIn" required={false}/><Field name="surfaceAvailable" label="Surface disponible (m²)" type="number" required={false}/><Field name="preciseLocation" label="Localisation précise" required={false}/><Field name="humanResources" label="Ressources humaines" type="number" required={false}/><Field name="estimatedBudget" label="Budget annuel estimé" required={false}/></div></details><button className="submit" disabled={sent==="loading"}>{sent==="loading"?t.loading:t.send}<Send size={18}/></button>{sent==="ok"&&<p className="status ok">Merci. Votre demande a bien été transmise.</p>}{sent==="error"&&<p className="status error">Envoi impossible. Vérifiez le serveur ou réessayez dans une minute.</p>}</form></section>
  <section className="locations">{data.locations.map(l=><div key={l.id}><small>{l.countryCode}</small><h3>{l.city}</h3><p>{l.address}</p></div>)}</section>
  <footer className="footer"><a className="brand" href="#top"><span className="brandMark"><i/><i/><i/></span><b>INTELLCAP</b></a><p>Deep Tech. Human ambition. Tangible impact.</p><span>© {year} INTELLCAP</span></footer>
 </main>;
}
function SectionTitle({kicker,title,subtitle}:{kicker:string;title:string;subtitle:string}){return <div className="sectionTitle"><p>{kicker}</p><div><h2>{title}</h2><span>{subtitle}</span></div></div>}
function Field({name,label,type="text",pattern,required=true}:{name:string;label:string;type?:string;pattern?:string;required?:boolean}){return <label className="field"><span>{label}</span><input name={name} type={type} pattern={pattern} required={required}/></label>}
